use_frameworks!
platform :ios, '11.0'

target 'SimpleKit_Example' do
  pod 'SimpleKit', :path => '../'

  target 'SimpleKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
